### ISSUE TITLE
Build fails due to missing C++ symbols during link when integrated via CocoaPods

### ISSUE THREAD

**Issue by zygoat** [pixelglow/zipzap#92]
With zipzap 8.0.2 integrated via CocoaPods, the project fails to link due to some apparently-missing C++ symbols referenced by a couple of classes:

```
Undefined symbols for architecture i386:
  "std::terminate()", referenced from:
      ___clang_call_terminate in libPods-Kashoo-zipzap.a(ZZAESDecryptInputStream.o)
  "___cxa_begin_catch", referenced from:
      ___clang_call_terminate in libPods-Kashoo-zipzap.a(ZZAESDecryptInputStream.o)
  "___gxx_personality_v0", referenced from:
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZArchive.o)
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZNewArchiveEntryWriter.o)
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZOldArchiveEntry.o)
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZOldArchiveEntryWriter.o)
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZNewArchiveEntry.o)
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZAESDecryptInputStream.o)
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZStandardDecryptInputStream.o)
      ...
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZArchive.o)
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZNewArchiveEntryWriter.o)
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZOldArchiveEntry.o)
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZOldArchiveEntryWriter.o)
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZNewArchiveEntry.o)
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZAESDecryptInputStream.o)
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZStandardDecryptInputStream.o)
      ...
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZArchive.o)
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZNewArchiveEntryWriter.o)
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZOldArchiveEntry.o)
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZOldArchiveEntryWriter.o)
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZNewArchiveEntry.o)
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZAESDecryptInputStream.o)
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZStandardDecryptInputStream.o)
      ...
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZArchive.o)
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZNewArchiveEntryWriter.o)
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZOldArchiveEntry.o)
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZOldArchiveEntryWriter.o)
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZNewArchiveEntry.o)
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZAESDecryptInputStream.o)
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZStandardDecryptInputStream.o)
      ...
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZArchive.o)
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZNewArchiveEntryWriter.o)
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZOldArchiveEntry.o)
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZOldArchiveEntryWriter.o)
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZNewArchiveEntry.o)
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZAESDecryptInputStream.o)
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZStandardDecryptInputStream.o)
      ...
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZArchive.o)
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZNewArchiveEntryWriter.o)
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZOldArchiveEntry.o)
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZOldArchiveEntryWriter.o)
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZNewArchiveEntry.o)
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZAESDecryptInputStream.o)
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZStandardDecryptInputStream.o)
      ...
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZArchive.o)
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZNewArchiveEntryWriter.o)
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZOldArchiveEntry.o)
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZOldArchiveEntryWriter.o)
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZNewArchiveEntry.o)
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZAESDecryptInputStream.o)
      Dwarf Exception Unwind Info (__eh_frame) in libPods-Kashoo-zipzap.a(ZZStandardDecryptInputStream.o)
      ...
      ...
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This appears to be related to the absence of `-fno-objc-exceptions` in the `compiler_flags` pertaining to the Obj-C++ sources in the Podfile, a change introduced in https://github.com/pixelglow/zipzap/commit/d0a33d6fd96c311b3010bf4b3e855a93e65280ee.

**Comment by pixelglow** [comment]
We avoid C++ exceptions to avoid having to link in the C++ runtime, libc++. See @00b7925.

Now it looks like in Objective-C++ code, we need `-fno-objc-exceptions` as well as `-fno-exceptions` to get this. Strangely enough though, `pod` compiles plain C++ code as Objective-C++ code, so adding `-fno-objc-exceptions` to the Objective-C++ subspec triggers the "unused argument" build warning for plain C++ code. See @d0a33d6.

The fix (hopefully!) is to break out another subspec for C++ with just `-fno-exceptions` and put `-fno-objc-exceptions` back into the Objective-C++ subspec.

I'll push the fix up here, please confirm it works for you, then I'll push it to pod trunk.

**Comment by zygoat** [comment]
Looks good—this now builds again for me. Thanks!

**Comment by pixelglow** [comment]
Tagged and pushed to pod trunk. 8.0.3 should be publicly available in CocoaPods soon.

**Comment by garyganyang** [comment]
it still failed in 8.0.4, after i change back to 8.0.3, it works again.
