### ISSUE TITLE
'Undefined symbols for architecture' when included using Cocoapods

### ISSUE THREAD

**Issue by rwbutler** [pixelglow/ZipZap#105]
ZipZap 8.0.4 no longer builds when included as part of an iOS project using Cocoapods, giving the compiler error:

Undefined symbols for architecture arm64:
  "___cxa_begin_catch", referenced from:
      ___clang_call_terminate in libPods-Ally-zipzap.a(ZZArchive.o)
  "std::terminate()", referenced from:
      ___clang_call_terminate in libPods-Ally-zipzap.a(ZZArchive.o)
  "___gxx_personality_v0", referenced from:
      +[ZZArchive archiveWithURL:error:] in libPods-Ally-zipzap.a(ZZArchive.o)
      +[ZZArchive archiveWithData:error:] in libPods-Ally-zipzap.a(ZZArchive.o)
      -[ZZArchive initWithURL:options:error:] in libPods-Ally-zipzap.a(ZZArchive.o)
      -[ZZArchive initWithData:options:error:] in libPods-Ally-zipzap.a(ZZArchive.o)
      -[ZZArchive initWithChannel:options:error:] in libPods-Ally-zipzap.a(ZZArchive.o)
      -[ZZArchive loadCanMiss:error:] in libPods-Ally-zipzap.a(ZZArchive.o)
      -[ZZArchive updateEntries:error:] in libPods-Ally-zipzap.a(ZZArchive.o)
      ...
ld: symbol(s) not found for architecture arm64

The issue appears to be due to compiler flags being removed which were present in 8.0.3.

Full documentation of the issue can be found here:

http://stackoverflow.com/questions/31348666/xcode-6-4-breaks-project-with-zipzap-dependency/31452591#31452591

**Comment by pixelglow** [comment]
Can you try with CocoaPods 0.38.0 or later? I used the attribute `pod_target_xcconfig` which only works with 0.38.0 or later, this attribute removes exception handling for ZipZap so that you don't have to link in libc++.

Alternatively you can also use Carthage, which is less intrusive than CocoaPods while requiring slightly more integration effort.

**Comment by rsanchezsaez** [comment]
By the way, I think that installing *ZipZap 8.0.4* with *Cocoapods 0.38.0* makes [Issue #78](https://github.com/pixelglow/zipzap/issues/78) to reoccur: exceptions are disabled project-wide.

Going back to *ZipZap 8.0.3* fixes it.

**Comment by rwbutler** [comment]
Thanks for the reply, updating does seem to resolve the initial issue. However can confirm that that after updating to Cocoapods 0.38.0 [Issue #78](https://github.com/pixelglow/zipzap/issues/78) reoccurs as stated by [rsanchezsaez](https://github.com/rsanchezsaez). Projects containing `try... catch` will fail to compile with Objectice-C exceptions disabled.

**Comment by pixelglow** [comment]
@rwbutler I can repro the issue and have submitted it to the CocoaPods team for a further look.

**Comment by rwbutler** [comment]
@pixelglow Excellent thanks.

**Comment by pixelglow** [comment]
Quick update folks: CocoaPods team have committed a fix but it's not yet in the release CocoaPods. If any of you are brave enough to try the development version of CocoaPods, do tell me if the issue has really been fixed.

**Comment by pixelglow** [comment]
Moving discussion to #118, since it has the more descriptive title.
